### PR TITLE
BO: Option added to anonymize visitor’s IP

### PR DESCRIPTION
**Pull request by skolarianer**
- Option 'anonymizeIp' added (as required by some countries’ data privacy laws)
- 'radio' -> 'switch' for both options
- tab-structure modified and line breaks added for a clean <script>-output

### CODE REVIEW

**Comment by justb81** [comment]
@manfield could you accept this PR, please? It is against the law in Europe to not use anonymizeip setting!

**Comment by kpodemski** [comment]
cc @Quetzacoalt91

**Comment by kpodemski** [comment]
Hey @eternoendless 

as you guys made hell of the progress with the project i suggest to do a quick round over modules pull requests, or maybe add a few hours per week to do that regulary, most of the time PR for modules are completely ignored or forgotten for weeeks, months and years...

**Comment by Quetzacoalt91** [comment]
Hmm, while I was fixing the conflicts for you, it appeared the feature was already available on the repository. I don't understand why it was still opened.

See https://github.com/PrestaShop/ps_googleanalytics/commit/b5f9bef1cd82034b16ecc0a5901539ca982b3492 for more details.

Thanks!

**Comment by eternoendless** [comment]
Hi @kpodemski 

Yeah, as your probably noticed, we are really struggling to keep up with the number of PRs + our own work. But we are looking for ways to improve our response time in the future.

Don't hesitate to ping us if you see something interesting or important that needs our attention!

**Comment by eternoendless** [comment]
Oh, I forgot to mention, we are also going to make a pass through the native modules to make sure they pass the validator (ahem). The core team is also growing, so expect more people doing reviews soon 😄

**Pull request closed without merging**
