### PR TITLE
Bump min compatibility to PHP 7.1.3 and PS 1.7.7

### PR DESCRIPTION
**Pull request by leemyongpakvn**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Please check the related issue. <br /> This PR need to be merged in Release 5.0.0 to avoid bumping to Release 6.0.0 **without** major functioning changes
| Type?             | refactor
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | Fixes PrestaShop/Prestashop#32841
| Sponsor company   | Your company or customer's name goes here (if applicable).
| How to test?      | CI green. Module works as usual on PS 1.7.7 and newer versions.

### CODE REVIEW

**Comment by Hlavtox** [comment]
Why remove all the use statements?

**Comment by leemyongpakvn** [comment]
@Hlavtox It is an auto fix by php-cs-fixer **v3**. You can see details in [the 3rd commit](https://github.com/PrestaShop/ps_googleanalytics/pull/154/commits/d65545e62fae120d5d3b1c7cfad4eea8243556fd). I guess php-cs-fixer v3 try to eliminate all use without namespace that php-cs-fixer **v2** left before.

**Review by matthieu-rolland — COMMENTED** [review]
LGTM overall, but I'm also skeptical about the removal of `use` statements 🤔

**Review by tleon — APPROVED** [review]
The removal of the use does not bother me with the added `\` it is just a matter of preferences. Personaly i'm used to the `\`.

**Comment by AureRita** [comment]
Hi ! 

Since the issue has been validated by devs, this pull request must be validated by devs

**Review by Hlavtox — CHANGES_REQUESTED** [review]
@leemyongpakvn Please wait until this is merged - https://github.com/PrestaShop/ps_googleanalytics/pull/153 or I will need to manually change million things when rebasing :D

**Comment by leemyongpakvn** [comment]
@Hlavtox OK. Rebase PR 513 is more difficult than rebase this one.

**Comment by leemyongpakvn** [comment]
@Hlavtox Is it the time to proceed with this PR? Fortunately, there is no new git conflict after PR 513 merged.

**Comment by Hlavtox** [comment]
Well I am waiting for @PrestaShop/qa-functional to do QA on https://github.com/PrestaShop/ps_googleanalytics/pull/153

**Comment by leemyongpakvn** [comment]
@Hlavtox Rebased. 
`\ prefixes` is forced by php-cs-fixer 3. CI is green now. I will try using `Ps_Googleanalytics` without `\` 5 minutes later, then I pretty sure that we will have CI red by PHP-CS-Fixer

**Comment by leemyongpakvn** [comment]
After [the fifth commit](https://github.com/PrestaShop/ps_googleanalytics/pull/154/commits/784a57ac02346390d99e763edb586f0a2dcfdf2a) to try old CS v2, CI really become Red by PHP-CS-Fixer.

**Comment by Hlavtox** [comment]
@leemyongpakvn What if you try to change this rule https://cs.symfony.com/doc/rules/import/global_namespace_import.html in php-cs-fixer.dist.php?

**Comment by Hlavtox** [comment]
@leemyongpakvn Or even better, we can fix it globally here - https://github.com/PrestaShop/php-dev-tools/blob/master/src/CsFixer/Config.php :-)

**Comment by leemyongpakvn** [comment]
@Hlavtox Thanks for your information. It will take time to adapt CSFixer config while you are in urgent need of Release 5.0.0 ;)
So let's go with only PHP and PS version bumps in this major version, I will try CSfixer config fix in a minor version.

**Review by Hlavtox — APPROVED** [review]

**Pull request merged**
