### PR TITLE
Add missing domains and use trans instead of l

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Add missing domains and use trans instead of l
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | ~
| How to test?      | ~
| Possible impacts? | ~

### CODE REVIEW

**Review by atomiix — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
@PrestaShop/qa-team 

Hello QA Team. What do you want to do with this PR? It shouldn't have any impact on the functional side of things.

**Review by matks — APPROVED** [review]

**Review by FabienPapet — APPROVED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi @kpodemski @jolelievre !

For the QA, just automated test can be launched :)

**Comment by Robin-Fischer-PS** [comment]
Oops, did not saw it was on a module. It can be merged without QA then.

**Comment by jolelievre** [comment]
Module tested, just a quick fix was necessary for ConfigurationForm because the `Module::trans` is not public. All works fine now, including switching language.

**Pull request merged**
