### PR TITLE
Fix PHP 5 compatibility

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Fixes PHP 5 compatibility.
| Type?             | refactor
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/ps_googleanalytics/pull/131#issuecomment-1460358549
| Sponsor company   |
| How to test?      |

### CODE REVIEW

**Comment by Hlavtox** [comment]
@MrThrust Bro could you check if this fixes your issue? Removing the type hints from these two functions?

**Comment by MrThrust** [comment]
Hey @Hlavtox I downloaded the php5
https://github.com/Hlavtox/ps_googleanalytics/tree/php5

but I didn't even get to install the module, there was a fatal error during installation..

```
[PrestaShop] Fatal error in module file :/home/amggroup/campingspares/modules/ps_googleanalytics/ps_googleanalytics.php:
Class 'PrestaShop\Module\Ps_Googleanalytics\Handler\ModuleHandler' not found
```

**Comment by MrThrust** [comment]
Thanks Hlavtox, I can confirm that method worked, Thank you!
I have successfully went through my entire checkout process with no issues!..

The only other issue I spotted was within the back office -> config page, trying to set the "canceled order status" value...

This never shows any value within the box, the dropdown works, lists all status types, 
selecting "cancel" from the list & save, the page will reload & show all success notifications... 

×Account ID updated successfully
×Settings for Google Analytics 4 updated successfully
×Settings for User ID updated successfully
×Settings for Anonymize IP updated successfully
×Settings for Enable Back Office tracking updated successfully.
×Settings for canceled order states updated successfully.

but the value for "canceled order states" wont show again in the box.
not a big deal, the value is set within the database.. just not showing in the backoffice.

**Comment by Hlavtox** [comment]
@MrThrust I think I based this PR on a wrong branch, it doesn't include the latest fixes. Don't worry, it will work like the 4.2.0 release. :-)

**Pull request merged**
