### PR TITLE
Release 4.2.2

### PR DESCRIPTION
**Pull request by lartist**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Release 4.2.2
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | 
| Sponsor company   | 
| How to test?      | Test the whole module

### CODE REVIEW

**Review by 0x346e3730 — APPROVED** [review]

**Review by matthieu-rolland — COMMENTED** [review]
phpstan failing, LGTM otherwise

**Review by Hlavtox — CHANGES_REQUESTED** [review]
Wording typo, quotes after dot.

Is it really necessary to release and test whole module because one wording change?

**Comment by lartist** [comment]
>Wording typo, quotes after dot.

Hi @Hlavtox, thanks for reporting the typo. I'm going to change it.

>Is it really necessary to release and test whole module because one wording change?

I totally agree with you, releasing and testing the whole module is a bit huge for a wording change. Unfortunately we have to. The 8.1.0 is coming soon and we have to extract the catalog of wordings. The way the extraction works is the following:

PrestaShop/PrestaShop is downloaded by [TranslationTool](https://github.com/PrestaShopCorp/TranslationTool) every built-in modules are installed with composer and then the extraction processes on the CORE AND the modules.

If we want an exhaustive catalog we have to release this version and if it occurs on another module we will do the same thing, even if it's for only one wording.

Maybe the extraction process can be improved. If you have any idea feel free to suggest it ;)

**Comment by lartist** [comment]
Fix of typo here https://github.com/PrestaShop/ps_googleanalytics/pull/147

**Review by Hlavtox — APPROVED** [review]

**Review by AureRita — APPROVED** [review]
Hi @lartist 

Thank you for your PR, I tested it and it seems to works as expected, as you can see : 

image

image

**Review by matthieu-rolland — APPROVED** [review]
Can we merge or should we wait @lartist ?

**Pull request merged**
