### PR TITLE
Release 4.2.1

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Release 4.2.1
| Type?             |
| BC breaks?        |
| Deprecations?     |
| Fixed ticket?     |
| Sponsor company   |
| How to test?      | I think it does not need QA.

#### 1. This PR fixes an issue with PHP 5.6, which does not support `string` type hints.
https://github.com/PrestaShop/ps_googleanalytics/pull/134#issuecomment-1462149107

#### 2. And adds a condition to backoffice refund, which fixes automated tests.
```
if (!Validate::isLoadedObject($orderDetail)) {
    return;
}
```
Before - https://capture.dropbox.com/AOvAgmA37e9bf82T
After - https://capture.dropbox.com/tDsM80VcO9ZpCLQZ

### CODE REVIEW

**Review by kpodemski — APPROVED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @Hlavtox ,

The upgrade to 4.2.1 is not effective, could you check ?

Thanks 🤗

**Comment by Hlavtox** [comment]
@florine2623 You can test now, we forgot to bump the version. :-)

**Comment by florine2623** [comment]
Thanks @Hlavtox ,
The upgrade went well 👍 

I also noticed that on versions 8.0.0 and superior, the switch button label is not displayed for Enabling Google Analytics 4 :
Screenshot 2023-03-15 at 10 45 39
It is only displayed after a first Edit :

https://user-images.githubusercontent.com/16019289/225272322-0a9c3154-ecc0-40f4-a4a8-9199051504b1.mov

It is QA ✅

**Comment by nicosomb** [comment]
Thank you @Hlavtox

**Pull request merged**
