### PR TITLE
Fix file permissions non-executable

### PR DESCRIPTION
**Pull request by dkarvounaris**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | <p>Incorrectly set executable flag causing issues in Git Bash under Windows</p><p>This ticket reports that several files in the repository, including images, have the executable flag set unnecessarily, causing issues when transferring the repository using Windows + Git Bash. This results in Git incorrectly identifying the files as modified, when in fact the only difference is the permission mode. Consequently, pulling changes to the repository is impossible, and Git prompts for merging changes. Moreover, setting the executable flag on these files makes them vulnerable to be called as executables under Linux. To address these issues, this commit sets the proper file permissions for all affected files to 0644, which removes the executable flag from these files.</p>
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | <p>To test the removal of the executable flag in Git Bash under Windows, first, reset the local Git repository to the previous commit using the following command:</p><p>`git reset --hard HEAD^`</p><p>Next, try to pull changes from the remote repository, which leads to the error. Try to remove the executable flag from the affected file using `chmod -x <file-name>`. Try to pull changes again, which proves this is not sufficient under Git Bash/Windows, as linux permissions are only "virtual" here and the error persists. </p><p>After the pull request, working with the repository, pulling changes and committing new files is working as intended.</p>

## Problem Description

Several files in the repository, including images, have the executable flag set unnecessarily. This flag causes issues when transferring the repository using Windows + Git Bash. As a result, **Git incorrectly identifies the files as modified, when in fact, the only difference is the permission mode**. Consequently, pulling changes to the repository is impossible, and Git prompts for merging changes. Moreover, **setting the executable flag on these files makes them vulnerable** to be called as executables under Linux.

The following screenshots attempt to visualize the issue in detail:

Permissions under Linux (`index.php`, `logo.png`, `ps_googleanalytics.php`, `ajax.php` - only some as example):
image

Permissions under Git Bash (Windows) - even with a fresh clone:
image

Issue during pulling changes:
image

Examining differences:
image

Files affected by executable permission set:
image

## Solution

To resolve these issues, this commit sets the proper file permissions for all affected files to 0644. This action removes the executable flag from the files, which serves no purpose and makes them vulnerable to attack under Linux, by utilizing: `git add --chmod=-x controllers/front/ajax.php ...(other files)`. This is the only contribution of the pull request. By removing the executable flag, Git will no longer prompt for merging changes, allowing for proper repository usage and management under Windows + Git Bash.

## Conclusion

This issue is related to the executable flag on several files within the repository, causing issues in Git Bash under Windows. The solution is to remove the executable flag from these files, which will resolve the merging issue and prevent potential security vulnerabilities under Linux.

### CODE REVIEW

**Comment by dkarvounaris** [comment]
This is a required prerequisite for some other issues I would to contribute, as recently identified with the new changes for supporting Google Analytics 4.

**Comment by Hlavtox** [comment]
As I didn't encounter any issues on Windows, I will leave the review to my peers - can't test it. :-)

Ping @PrestaShop/committers

**Comment by dkarvounaris** [comment]
@Hlavtox I'm not sure how to check or even solve the CI, honestly, or I would look at it. I don't even know in this matter, to confirm if it's the permission change causing it or something else. 

This is just a permissions change though (besides being a security concern too), which should have no side effect on anything normally. But one, which would allow me to not have to "clean up" the other pull requests (once I'm done), which involves rebasing, for the purpose of picking and dropping commits and forcefully pushing. And I did not wanted to simply "hide" this change to the other unrelated PR's, as unimportant it seems, to be able to commit my changes on my windows machine. This one commit is unfortunately on my other drafted PR too at the moment, but only because it has to be, and I was planning to "clean" up the other PR once I would mark it as no draft. Having this merged, would just make all this extra effort and the possible confusion unnecessary, though.

**Comment by dkarvounaris** [comment]
@Hlavtox I was too quick to comment. You were right, I did oversee that there is one *.sh script, which requires the executable bit, unlike .php and .png's. I fixed it.

**Review by matks — APPROVED** [review]
Hello everyone I confirm the security standard is
- 644 for files
- 755 for directories

Also CI seems to be green now 😄

**Comment by matks** [comment]
As the code has not been changed 🤔 (only access controls) I believe there is nothing to be tested by QA. The code is exactly the same as before.

**Comment by matks** [comment]
Thank you @dkarvounaris

**Pull request merged**
